"""SceneBehaviorGraph assembly and persistence helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..utils.ids import slugify
from ..utils.json_io import write_json


class SceneBehaviorGraphWriter:
    def assemble(self, state: dict[str, Any]) -> dict[str, Any]:
        scene_id = state.get("scene_id") or state.get("scene_facts", {}).get("scene_id", "unknown_scene")
        now = datetime.now(timezone.utc).isoformat()
        graph = {
            "schema_id": f"scene_behavior_graph_{slugify(scene_id)}_v0_2",
            "schema_type": "SceneBehaviorGraph",
            "version": "0.2.0",
            "name": f"SceneBehaviorGraph for {scene_id}",
            "description": "Agent generated SceneBehaviorGraph draft.",
            "source": {
                "kind": "langgraph_agent_generated",
                "agent_run_id": state.get("run_id"),
                "created_at": now,
            },
            "created_for": "自然语言驱动的场景行为仿真建模。",
            "references": [
                "docs/business/SimulationSchema/1.DeviceSpec/schema.json",
                "docs/business/SimulationSchema/2.SceneDocument/schema.json",
                "docs/business/SimulationSchema/4.SceneBehaviorGraph/schema.json",
            ],
            "notes": [
                "Generated by agent/scene_behavior_agent.",
                "Runtime scheduling is executed by downstream Runtime Scheduler, not by this agent.",
            ],
            "goal": state.get("intent", {}),
            "modules": state.get("process_modules", []),
            "event_bus": state.get("event_bus_draft", {"events": [], "routes": []}),
            "state_model": state.get("state_model_draft", {}),
            "behavior_rules": state.get("behavior_rules_draft", []),
            "state_transition_rules": state.get("state_transition_rules_draft", []),
            "policies": state.get("policies_draft", {}),
            "completion_conditions": state.get("completion_conditions_draft", []),
            "failure_observations": state.get("failure_observations_draft", []),
        }
        return graph

    def write(self, output_path: str | Path, graph: dict[str, Any]) -> None:
        write_json(output_path, graph)
